const cardTypes = {
  SET_MESSAGE: "SET_MESSAGE",
  SET_TEXT_ISVISIBLE: "SET_TEXT_ISVISIBLE",
  SET_MENU_STICKER_ISVISIBLE: "SET_MENU_STICKER_ISVISIBLE",
  SET_MENU_BACKGROUND_ISVISIBLE: "SET_MENU_BACKGROUND_ISVISIBLE",
  SET_MENU_TEXT_ISVISIBLE: "SET_MENU_TEXT_ISVISIBLE",

  SET_BACKGROUND_COLOR: "SET_BACKGROUND_COLOR",
};

const types = {
  ...cardTypes,
};

export default types;
