const cardTypes = {
  SET_MESSAGE: "SET_MESSAGE",
  SET_TEXT_ISVISIBLE: "SET_TEXT_ISVISIBLE",
  SET_MENU_STICKER_ISVISIBLE: "SET_MENU_STICKER_ISVISIBLE",
  SET_MENU_BACKGROUND_ISVISIBLE: "SET_MENU_BACKGROUND_ISVISIBLE",
  SET_MENU_TEXT_ISVISIBLE: "SET_MENU_TEXT_ISVISIBLE",

  SET_BACKGROUND_COLOR: "SET_BACKGROUND_COLOR",
  SET_BACKGROUND_IMAGE: "SET_BACKGROUND_IMAGE",
  REMOVE_BACKGROUND_IMAGE: "REMOVE_BACKGROUND_IMAGE",

  ADD_STICKER: "ADD_STICKER",
  REMOVE_STICKER: "REMOVE_STICKER",
  SET_STICKER_POS: "SET_STICKER_POS",
<<<<<<< HEAD
=======
  SET_STICKER_SCALE: "SET_STICKER_SCALE",

  SET_CARD_ID: "SET_CARD_ID",
>>>>>>> ce45131251102bfaa7aa41d6ee6ac3b486443c22
};

const types = {
  ...cardTypes,
};

export default types;
