# Generated by Django 3.2.12 on 2022-03-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('audio', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
