# Generated by Django 3.2.12 on 2022-03-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='myvoice',
            field=models.FileField(null=True, upload_to="str(card.card_id).replace('-', '')"),
        ),
        migrations.AlterField(
            model_name='card',
            name='audio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
