# Generated by Django 3.2.12 on 2022-03-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='id',
            new_name='card_id',
        ),
    ]
