# Generated by Django 3.2.12 on 2022-03-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_id_card_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='audio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='card',
            name='video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
