# Generated by Django 3.2.12 on 2022-03-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20220321_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
