# Generated by Django 3.2.12 on 2022-03-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='createAt',
        ),
    ]
