# Generated by Django 3.2.12 on 2022-03-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_remove_card_createat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
