# Generated by Django 3.2.12 on 2022-03-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='audio',
            field=models.FileField(null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='card',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
    ]
