# Generated by Django 3.2.12 on 2022-03-22 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20220321_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
