# Generated by Django 3.2.12 on 2022-03-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20220321_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
